### ISSUE TITLE
react-native example doesn't work with Android?

### ISSUE THREAD

**Issue by xRiot** [rocwind/react-native-webview-comlink#387]
I gave the `examples/native` a shot on my Samsung Galaxy S8+ android device but the app complains about not being able to connect to Metro server. I've tried reversing adb ports with no success and installing exact package versions from packages.json to no avail.

Is  the Android example incomplete?

**Comment by rocwind** [comment]
@xRiot 
The Android example should be able to work (just checked about it with a fresh install). It looks like the android device was having trouble to connect to metro server according to your description, and there are something that might worth a try in my mind:
- make sure the metro(debug) server it running on 8081 port;
- there is no proxy set for the android device (or `localhost` should be put to the bypass proxy list);
- try connect the metro server by input ip address in app "settings" > "Debug server host & port" and restart the app;

**Comment by xRiot** [comment]
Thanks for the troubleshooting tips @rocwind! These works like a charm in any other project but unfortunately I can't get it to work on my macOS 10.15.6 / Android 9 with this project. Since you can't reproduce it, it's most likely related to my dependencies/environment.
